export const FIRST_NAME = [
    'Sigurd',
    'Astrid',
    'Erik',
    'Freya',
    'Ragnar',
    'Gudrun',
    'Bjorn',
    'Helga',
    'Leif',
    'Ingrid',
    'Sven',
    'Thora',
    'Olaf',
    'Ragna',
    'Haldor',
    'Sigrid',
    'Arne',
    'Jorunn',
    'Hakon',
    'Aslaug',
    'Kjartan',
    'Ylva',
    'Toste',
    'Hilde',
    'Vagn',
    'Solveig',
    'Arvid',
    'Inga',
    'Knute',
    'Ulfhild',
    'Einar',
    'Dagmar',
    'Gorm',
    'Skadi',
    'Halvard',
    'Ingeborg',
    'Magnus',
    'Unn',
    'Thorstein',
    'Sigrun',
];

export const LAST_NAME = [
    'Blood-Axe',
    'Sea-King',
    'Shield-Bearer',
    'Iron-Fist',
    'Wind-Walker',
    'Storm-Eye',
    'Fire-Heart',
    'Wolf-Skin',
    'Raven-Feeder',
    'Serpent-Tongue',
    'Snow-Hair',
    'Ice-Vein',
    'Bearclaw',
    'Rune-Caster',
    'Battle-Cry',
    'Dragon-Slayer',
    'Sea-Strider',
    'Spear-Breaker',
    'Earth-Shaker',
    'Storm-Caller',
];

export const NICKNAME = [
    'the Bold',
    'the Fearless',
    'the Fierce',
    'the Wise',
    'the Cunning',
    'the Swift',
    'the Strong',
    'the Beautiful',
    'the Blessed',
    'the Cursed',
    'the Peaceful',
    'the Wrathful',
    'the Vengeful',
    'the Mighty',
    'the Skald',
    'the Seer',
    'the Shield-Bearer',
    'the Wolf',
    'the Sea Eagle',
    'the Serpent',
];
